source 'http://rubygems.org'

gem 'rails', '3.2.12'

group :assets do
  gem 'sass-rails', "~> 3.2.3"
  gem 'coffee-rails', "~> 3.2.1"
  gem 'uglifier', ">= 1.0.3"
end

group :development do
  gem 'sqlite3', :require => 'sqlite3'
end
group :production do
  gem 'pg'
  gem 'unicorn'
end

gem 'devise'
gem 'rake', '>= 0.8.7'
gem 'jquery-rails'
