source 'http://rubygems.org'

gem 'rails', '3.0.10'
group :development do
  gem 'sqlite3-ruby', :require => 'sqlite3'
end
group :production do
  gem 'pg'
  gem 'unicorn'
end

gem 'devise'
gem 'rake', '>= 0.8.7'
