#!/bin/bash
## system start daemon for unicorn

PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
DESC="Unicorn Application Server"
DAEMON=/usr/local/bin/unicorn
NAME=unicorn
USER=freeswitch
WORKDIR=/usr/local/freeswitch/webapp/
PIDFILE=$WORKDIR/$NAME.pid

UNICORN_PARAMS="-o 127.0.0.1 -p 3000 -D"

CALLEDSCRIPT=`basename $0`

do_start()
{
  # Return
  #   0 if daemon has been started
  #   1 if daemon was already running
  #   2 if daemon could not be started
  start-stop-daemon -d $WORKDIR -c $USER --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
    || return 1
  start-stop-daemon -d $WORKDIR -c $USER --start --quiet --pidfile $PIDFILE --exec $DAEMON -- \
  $UNICORN_PARAMS \
  || return 2
}


do_stop()
{
  start-stop-daemon -d $WORKDIR -c $USER --stop --quiet --pidfile $PIDFILE --name $NAME
  return "$?"
}

case "$1" in
  start)
    log_daemon_msg "Starting $DESC" "$NAME"
    do_start
    ;;
  stop)
    log_daemon_msg "Stopping $DESC" "$NAME"
    do_stop()
    ;;
  restart)
    log_daemon_msg "Restarting $DESC" "$NAME" 
    do_stop
    case "$?" in
      0|1)
        do_start
      ;;
      *)
        log_end_msg 1
      ;;
    esac
    ;;
  *)
    echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
    exit 3
    ;;
esac

:
